[package]
name = "const-bounded-collections"
version = "0.10.0"
license = "CC0-1.0"
edition = "2024"
description = "Rust Vec wrapper with type guarantees on lower and upper bounds for items quantity."
repository = "https://github.com/n1xyz/const-bounded-collections"

[dependencies]
serde = { version = "1.0", default-features = false, features = [
    "alloc",
    "derive",
], optional = true }
schemars = { version = "1.2.0", default-features = false, optional = true }
thiserror = { version = "2", default-features = false }
proptest = { version = "1.11", optional = true }
borsh = { version = "1.6", default-features = false, optional = true }
kitness = { git = "https://github.com/dzmitry-lahoda/kitness", rev = "8bec62fca015c27a1263b48332ca57d5e0995c7f", default-features = false }

[features]
serde = ["dep:serde", "kitness/json"]
schemars = ["serde", "dep:schemars", "kitness/json"]
arbitrary = ["proptest"]
borsh = ["dep:borsh", "kitness/borsh"]
borsh_schema = ["borsh", "borsh/unstable__schema"]
panic = []
nightly = []

[dev-dependencies]
proptest = { version = "1.11" }
serde_json = { version = "1.0", default-features = false, features = ["std"]}
no-panic = { version = "0.1.37" }
